---
title: "Community Input"
jupyter: python3
execute:
  freeze: false
---

## Appendix A - Region Map {#sec-appendix-a-map}

*TODO: Add narrative for this section.f

## Appendix B - Dutchess County Map {#sec-appendix-b-map}

*TODO: Add narrative for this section.*

## Appendix C - Orange County Map {#sec-appendix-c-map}

*TODO: Add narrative for this section.f

## Appendix D - Putnam County Map {#sec-appendix-d-map}

*TODO: Add narrative for this section.*

## Appendix E - Rockland County Map {#sec-appendix-e-map}

*TODO: Add narrative for this section.*

## Appendix F - Sullivan County Map {#sec-appendix-f-map}

eTODO: Add narrative for this section.*

## Appendix G - Ulster County Map {#sec-appendix-g-map}

*TODO: Add narrative for this section.*

## Appendix H - Westchester County Map {#sec-appendix-h-map}

*TODO: Add narrative for this section.*

## Appendix I - Region Community Partner Survey {#sec-appendix-i-community-partner-survey}

*TODO: Add narrative for this section.*

## Appendix J - Region Community Partner Survey References {#sec-appendix-j-community-partner-survey-references}

*TODO: Add narrative for this section.*

## Appendix K - Putnam County and Nuvance CBO and Partner Survey {#sec-appendix-k-putnam-nuvance-cbo-survey}

*TODO: Add narrative for this section.*

## Appendix L - Regional Community Health Survey {#sec-appendix-l-mid-hudson-regional-community-health-survey}

*TODO: Add narrative for this section.*

## Appendix M - Orange County Community Health Survey {#sec-appendix-m-orange-county-community-health-survey}

*TODO: Add narrative for this section.*

## Appendix N - Orange County Community Asset Survey {#sec-appendix-n-orange-county-community-asset-survey}

*TODO: Add narrative for this section.*

## Appendix O - Putnam County and Nuvance Community Health Experience Survey {#sec-appendix-o-putnam-nuvance-community-health-experience-survey}

*TODO: Add narrative for this section.*

## Appendix P - Rockland County Community Health Assessment Survey {#sec-appendix-p-rockland-county-community-health-assessment-survey}

*TODO: Add narrative for this section.*

## Appendix Q - Greater New York Hospital Association 2025 Community Health Needs Assessment Survey {#sec-appendix-q-gnyha-2025-community-health-needs-assessment-survey}

*TODO: Add narrative for this section.*
