<!-- indicator: tbl-alcohol-mva-injury-death -->

```{python}
#| echo: false
#| warning: false
#| message: false
#| label: tbl-alcohol-mva-injury-death
#| tbl-cap: 'Alcohol Related Motor Vehicle Injuries and Deaths, Rate per 100,000 Population, 2018–2021'
from scripts.cha_registry_renderer import render_table_object
render_table_object(object_id="tbl-alcohol-mva-injury-death", workbook_path=CHA_WORKBOOK_PATH)
```

::: {.callout-note collapse="true"}
## Source
Note: Data include persons killed or injured in motor vehicle crashes where alcohol was considered to be a factor. It also includes pedestrians, bicyclists and all other non-vehicle involved persons as well as vehicle occupants. These data were gathered from police reports. Crashes are reported by the county where the event occurred. Three-year averages are used for Orange County and single-year estimates are used for the Mid-Hudson, NYS, and NYS excl NYC.
:::

::: {.callout-note}
Note: Data include persons killed or injured in motor vehicle crashes where alcohol was considered to be a factor. It also includes pedestrians, bicyclists and all other non-vehicle involved persons as well as vehicle occupants. These data were gathered from police reports. Crashes are reported by the county where the event occurred. Three-year averages are used for Orange County and single-year estimates are used for the Mid-Hudson, NYS, and NYS excl NYC.
:::
