<!-- indicator: tbl-self-inflict-injury-hospital-aar -->

```{python}
#| echo: false
#| warning: false
#| message: false
#| label: tbl-self-inflict-injury-hospital-aar
#| tbl-cap: 'Self Inflicted Injury Hospitalization, Age-Adjusted Rate per 10,000, 2018–2021'
from scripts.cha_registry_renderer import render_table_object
render_table_object(object_id="tbl-self-inflict-injury-hospital-aar", workbook_path=CHA_WORKBOOK_PATH)
```

::: {.callout-note collapse="true"}
## Source
NYS Community Health Indicator Reports Dashboard, August 2025 sourced from NY Statewide Planning and Research Cooperative System [https://webbi1.health.ny.gov/SASStoredProcess/guest?_program=%2FEBI%2FPHIG%2Fapps%2Fchir_dashboard%2Fchir_dashboard&](https://webbi1.health.ny.gov/SASStoredProcess/guest?_program=%2FEBI%2FPHIG%2Fapps%2Fchir_dashboard%2Fchir_dashboard&) p=ch&cos=33
:::

::: {.callout-note}
Note: ICD-10 requires coders to assign unintentional intent when the intent is not stated in the medical record. This may lead to an overcount of unintentional injuries and an undercount of intentional injuries, such as assaults and self-harm. Three-year averages are used for Orange County, and single-year estimates are used for the Mid-Hudson Region, NYS excl NYC, and NYS. beginning in data year 2016, the firstmentioned injury diagnosis code or the first-mentioned external cause code in the principal diagnosis field, any of external injury fields, or any of 24 other diagnosis fields was used to define injury types in the SPARCS data. The specific codes for each type of injury are listed in format catalogs https://ftp.cdc.gov/pub/Health_Statistics/NCHS/injury/tools/ on the NCHS site. The catalogs used for this CHIR dashboard are intent_fmt64b.sas7bcat and mechanism_fmt64b.sas7bdat (Accessed in November 2020). Please visit Injury Data and Resources for further ICD-10-CM information.
:::
