<!-- indicator: tbl-allbirths-medicaid-selfpay-age-rande-zip -->

```{python}
#| echo: false
#| warning: false
#| message: false
#| label: tbl-allbirths-medicaid-selfpay-age-rande-zip
#| tbl-cap: 'All Births with Medicaid or Self-Pay, by Age, Race and Ethnicity, and ZIP Code, 2020–2023'
from scripts.cha_registry_renderer import render_table_object
render_table_object(object_id="tbl-allbirths-medicaid-selfpay-age-rande-zip", workbook_path=CHA_WORKBOOK_PATH)
```

::: {.callout-note collapse="true"}
## Source
Special request from NYSDOH Bureau of Vital Records, July 2025
:::

::: {.callout-note}
*: Higher percentage of missing data than other zip codes. Interpret rates with caution. s: Data are suppressed due to not meeting reporting criteria. Note: See Data Note section for more information regarding this request. Medicaid includes managed care, Prenatal Care Assistance Program, Medicaid Obstetrical and Maternal Services, and Family Health Plus. Self-pay includes mothers who have no identified third-party health insurance coverage. Birth and death data for Orange County excludes events recorded in NYC. Rates use ACS 5-year population estimates, except for the ages under 1 year and 1–9 years, which are based on crude live births in Orange County. Rates for race and ethnicity are calculated using ACS 2019 5-year population estimates.
:::
